<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
	<LangVersion>8.0</LangVersion>
	<Version>2.45.2.0</Version>
	<AssemblyVersion>2.45.2.0</AssemblyVersion>
	<FileVersion>2.45.2.0</FileVersion>
    <PackageId>librealsense.x64</PackageId>
	<Company>Intel®</Company>
    <Authors>Intel®</Authors>
    <Product>Intel® RealSense™ SDK</Product>
	<Copyright>Intel®</Copyright>
	<Description>Intel® RealSense™ cross-platform C# wrapper.</Description>
	<PackageProjectUrl>https://github.com/UMapx/Intel.RealSense</PackageProjectUrl>
	<RepositoryUrl>https://github.com/UMapx/Intel.RealSense</RepositoryUrl>
	<RepositoryType>git</RepositoryType>
	<PackageTags>intel realsense depth-camera computer-vision</PackageTags>
	<NeutralLanguage>en</NeutralLanguage>
	<PackageLicenseFile>LICENSE</PackageLicenseFile>
	<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
	<PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
	<PackageIcon>intelrealsense.png</PackageIcon>
	<PackageReadmeFile>README.md</PackageReadmeFile>
    <AssemblyName>Intel.RealSense</AssemblyName>
    <RootNamespace>Intel.RealSense</RootNamespace>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
	<DefineConstants>DEBUG;TRACE</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
	<GenerateDocumentationFile>true</GenerateDocumentationFile>
	<Optimize>true</Optimize>
	<DebugType>none</DebugType>
	<DebugSymbols>false</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
	<None Include="../README.md" Pack="true" PackagePath="/" />
    <None Include="intelrealsense.png">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
    <None Include="LICENSE">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <None Update="realsense2.dll">
      <Pack>true</Pack>
      <PackagePath>runtimes/win-x64/native/</PackagePath>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </None>
  </ItemGroup>

</Project>
